import fs from "fs";
import path from "path";
import { pathToFileURL } from "url";

const PLUGINS_DIR = "plugins";
const ROUTES_BASE = "src/routes";
const GENERATED_REGISTRY = "src/lib/plugin-registry.generated.ts";
const GITIGNORE_PATH = ".gitignore";
const MARKER_START = "# Auto-generated plugin routes";
const MARKER_END = "# End plugin routes";

interface PluginManifest {
    name: string;
    category: string;
    path: string;
    icon?: string;
}

// Discover plugins by scanning directories
const pluginDirs = fs
    .readdirSync(PLUGINS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

const plugins: Record<string, PluginManifest> = {};
const linkedRoutes: string[] = [];

for (const id of pluginDirs) {
    const manifestPath = path.resolve(PLUGINS_DIR, id, "manifest.ts");

    if (!fs.existsSync(manifestPath)) {
        console.log(`Skipping ${id}: no manifest.ts`);
        continue;
    }

    // Dynamic import the manifest
    const manifestUrl = pathToFileURL(manifestPath).href;
    const manifest = await import(manifestUrl);
    plugins[id] = manifest.default;

    // Create route symlink (strip "nexus-" prefix for cleaner URLs)
    const src = path.resolve(PLUGINS_DIR, id, "routes");
    const routeName = id.replace(/^nexus-/, "");
    const dest = path.resolve(ROUTES_BASE, routeName);

    if (!fs.existsSync(src)) {
        console.log(`Skipping ${id} routes: no routes directory`);
        continue;
    }

    // Remove existing
    if (fs.existsSync(dest) || fs.lstatSync(dest, { throwIfNoEntry: false })) {
        fs.rmSync(dest, { recursive: true, force: true });
    }

    // Create symlink
    const relative = path.relative(path.dirname(dest), src);
    fs.symlinkSync(relative, dest);
    console.log(`Linked: ${dest} -> ${relative}`);
    linkedRoutes.push(`${ROUTES_BASE}/${routeName}`);
}

// Generate runtime registry
const registryContent = `// Auto-generated by setup-plugins.ts - do not edit
export interface PluginManifest {
    name: string;
    category: string;
    path: string;
    icon?: string;
}

export const plugins: Record<string, PluginManifest> = ${JSON.stringify(plugins, null, 4)};
`;
fs.writeFileSync(GENERATED_REGISTRY, registryContent);
console.log(`Generated: ${GENERATED_REGISTRY}`);

// Update .gitignore
const pluginIgnores = [GENERATED_REGISTRY, ...linkedRoutes].join("\n");

let gitignore = fs.existsSync(GITIGNORE_PATH)
    ? fs.readFileSync(GITIGNORE_PATH, "utf-8")
    : "";

// Remove old plugin section
const startIdx = gitignore.indexOf(MARKER_START);
const endIdx = gitignore.indexOf(MARKER_END);
if (startIdx !== -1 && endIdx !== -1) {
    gitignore =
        gitignore.slice(0, startIdx) +
        gitignore.slice(endIdx + MARKER_END.length);
}

// Add new plugin section
gitignore =
    gitignore.trimEnd() +
    "\n\n" +
    MARKER_START +
    "\n" +
    pluginIgnores +
    "\n" +
    MARKER_END +
    "\n";

fs.writeFileSync(GITIGNORE_PATH, gitignore);
console.log("Updated .gitignore");

console.log(`\nDiscovered ${Object.keys(plugins).length} plugin(s)`);
